version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: playwright-test
    versions:
    - 1.2.0
    - 1.3.0
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 3.0.0
    - 3.0.4
    - 3.0.5
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: react-native-test-runner
    versions:
    - 4.0.0
    - 5.0.0
  - dependency-name: c8
    versions:
    - 7.7.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
  - dependency-name: tape
    versions:
    - 5.1.1
    - 5.2.0
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: sirv-cli
    versions:
    - 1.0.11
  - dependency-name: ini
    versions:
    - 1.3.8
