# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tests
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  chromium_linux:
    name: "Chromium Linux"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev
    - run: yarn
    - run: yarn test
    - run: yarn test:browser
    - run: yarn cov:report
    - uses: codecov/codecov-action@v1


  webkit_macos:
    name: "Webkit Mac"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: npx playwright-test --runner tape --browser webkit

  firefox_linux:
    name: "Firefox Linux"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: npx playwright-test --runner tape --browser firefox
